# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.mwifi123.com
basurl: /
title: 壮士
author: 壮士
description: Personal blog and resume
avatar: fabio.png
email: xiahao90@fexmail.com
github: xiahao90
twitter: xiahao90
google_analytics: UA-47728743-1

gitment:
  enable: true
  githubID: xiahao90
  repo: my_Gitment
  ClientID: 7fee1732777136072dc2
  ClientSecret: 949ea75cb8b49d928a03e66c9a90e1b3353607c1
  lazy: true
